# -*- coding: utf-8 -*-
"""finalreport2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wp4RFZ_eW1oyv4Fsqd-hZOkMJxmfxEd0
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/finalreport

from scipy.io.wavfile import read
import numpy as np
import copy

rate1, rawdata1 = read('music1.wav')
n1 = len(rawdata1)
data1 = copy.copy(rawdata1)

rate2, rawdata2 = read('music2.wav')
n2 = len(rawdata2)
data2 = copy.copy(rawdata2)

data = np.zeros((n1,2))
for i in range(n1):
  data[i][0] = data1[i]
  data[i][1] = data2[i]

cov_matrix = np.cov(data1,data2)
eigenvalues, unique_matrix = np.linalg.eig(cov_matrix)
matrix_D = [[eigenvalues[0]**(-0.5),0],[0,eigenvalues[1]**(-0.5)]]
matrix_V = unique_matrix @ matrix_D @ unique_matrix.T
z = np.zeros((n1,2))
for i in range(n1):
  z[i] = matrix_V @ data[i]

def regularize(w): #正規化をおこなう
  n = len(w)
  sum = 0
  for i in range(n):
    sum += w[i]**2
  for i in range(n):
    w[i] *= sum**(-0.5)
  return w

import copy

w1 = [1,5]
w2 = [-5,-1]

w1 = regularize(w1)
w2 = regularize(w2)
pastw1 = copy.copy(w1)  
pastw2 = copy.copy(w2) #収束確認用に前のwをコピーしておく

diff = 1 #収束確認用
while diff >= 0.000001:
  diff = 0
  sumE1_0 = 0
  sumE1_1 = 0
  for i in range(n1):
    sumE1_0 += (z[i][0] * np.inner(w1,z[i])**3)
    sumE1_1 += (z[i][1] * np.inner(w1,z[i])**3)
  E1 = [sumE1_0 / n1, sumE1_1 / n1]
  w1[0] = E1[0] - w1[0]*3
  w1[1] = E1[1] - w1[1]*3
  w1 = regularize(w1)
  for i in range(2):
    diff += abs(abs(pastw1[i])-abs(w1[i]))
  #1つ前のwからの変化量の合計、これが十分小さければ収束したと判断する
  pastw1 = copy.copy(w1)

diff = 1
while diff >= 0.000001:
  diff = 0
  sumE2_0 = 0
  sumE2_1 = 0
  for i in range(n1):
    sumE2_0 += (z[i][0] * np.inner(w2,z[i])**3)
    sumE2_1 += (z[i][1] * np.inner(w2,z[i])**3)
  E2 = [sumE2_0 / n1, sumE2_1 / n1]
  w2[0] = E2[0] - w2[0]*3
  w2[1] = E2[1] - w2[1]*3
  w2 = regularize(w2)
  for i in range(2):
    diff += abs(pastw2[i]-w2[i])
  pastw2 = copy.copy(w2)

W = [[w1[0],w1[1]],[w2[0],w2[1]]]

y = np.zeros((n1,2))

for i in range(n1):
  y[i] = W @ z[i]

y1 = np.zeros(n1)
y2 = np.zeros(n1)
for i in range(n1):
  y1[i] = y[i][0] * 5000
  y2[i] = y[i][1] * 5000

y1_int = y1.astype(np.int16)
y2_int = y2.astype(np.int16)

from scipy.io.wavfile import write
from IPython.display import Audio

write('separatedmusic1.wav', rate1, y1_int)
write('separatedmusic2.wav', rate1, y2_int)

Audio("music1.wav")

Audio("music2.wav")

Audio("separatedmusic1.wav")

Audio("separatedmusic2.wav")

from matplotlib import pyplot as plt
plt.plot(rawdata1)
plt.plot(y1_int)
plt.plot(y2_int)
plt.show()

